feat: requirements check.
Changelog: Title
Ticket: MEN-6368
Signed-off-by: Peter Grzybowski <peter@northern.tech>

diff --git a/src/app b/src/app
--- a/src/app
+++ b/src/app
@@ -52,8 +52,44 @@ if test -d "$PERSISTENT_STORE"; then
     fi
 fi
 
-delta_cmd="xdelta3 -d -s"
-tar_decompress_cmd="tar -xzvf"
+CONFIG_HAS_XDELTA3_CMD="xdelta3"
+CONFIG_HAS_TAR_CMD="tar"
+delta_cmd="${CONFIG_HAS_XDELTA3_CMD} -d -s"
+tar_decompress_cmd="${CONFIG_HAS_TAR_CMD} -xzvf"
+
+assert_requirements() {
+    local req_message
+    local command
+    local level
+    local COMMAND_NOT_FOUND_RC_THRESHOLD=100
+    local COMMAND_MISSING_ERROR_LEVEL="error"
+    local rc=0
+    local out_tmp
+
+    out_tmp=$(mktemp)
+    $app_sub_module REQS > "$out_tmp"
+    echo "${CONFIG_HAS_TAR_CMD}:error" >> "$out_tmp"
+    echo "${CONFIG_HAS_XDELTA3_CMD}:error" >> "$out_tmp"
+    set +e
+    while IFS=":" read -r command level; do
+        "$command" < /dev/null > /dev/null 2>&1
+        if test $? -gt $COMMAND_NOT_FOUND_RC_THRESHOLD; then
+            echo "$level cannot find required command $command on PATH."
+            if test "$level" = "$COMMAND_MISSING_ERROR_LEVEL"; then
+                # only if the sub-module reported error level on absence of the command we bail out
+                rc=1
+            fi
+        fi
+    done < "$out_tmp"
+    set -e
+    rm -f "$out_tmp"
+
+    if test $rc -eq 1; then
+        # exit here is on purpose, as per the name of the function the update module will exit with an error
+        exit $rc
+    fi
+    return 0
+}
 
 parse_metadata() {
     application_name=$(jq -r .application_name < "$1")
@@ -197,6 +233,7 @@ case "$STATE" in
 
     ArtifactInstall)
         parse_metadata "$FILES"/header/meta-data "$FILES"/header/header-info
+        assert_requirements
         handle_artifact "$FILES"/files
         ;;
 
