chore: fixes
Ticket: MEN-6077
Signed-off-by: Peter Grzybowski <peter@northern.tech>

diff --git a/src/app b/src/app
--- a/src/app
+++ b/src/app
@@ -188,9 +188,14 @@ handle_artifact() {
             fi
         fi
     done
-    mkdir -p "${PERSISTENT_STORE}/${application_name}"/images
-    rm -f "${PERSISTENT_STORE}/${application_name}"/images/*
+    if test -d "${PERSISTENT_STORE}/${application_name}"; then
+      rm -Rf "${PERSISTENT_STORE}/${application_name}-previous"
+      mv -v "${PERSISTENT_STORE}/${application_name}" "${PERSISTENT_STORE}/${application_name}-previous"
+    fi
+    mkdir -pv "${PERSISTENT_STORE}/${application_name}"/images
+    rm -vf "${PERSISTENT_STORE}/${application_name}"/images/*
     for image_dir in "${temp_dir}/images/"*; do
+        echo "scanning ${image_dir}"
         url_current=$(cat "${image_dir}/url-current.txt")
         url_new=$(cat "${image_dir}/url-new.txt")
         sha_new=$(cat "${image_dir}/sums-new.txt")
@@ -206,20 +211,38 @@ handle_artifact() {
     done
     # we should check if the app is healthy and alive, then decide what to do
     # at the moment we assume it is alive and ok
-    if test -d "${PERSISTENT_STORE}/${application_name}/"; then
-        mv -v "${PERSISTENT_STORE}/${application_name}/" "${PERSISTENT_STORE}/${application_name}-${rollback_id}"
-        $app_sub_module STOP "${application_name}" "${PERSISTENT_STORE}/${application_name}-${rollback_id}/manifests"
+    if test -d "${PERSISTENT_STORE}/${application_name}-previous"; then
+        echo "stopping ${PERSISTENT_STORE}/${application_name}-previous/manifests"
+        $app_sub_module STOP "${application_name}" "${PERSISTENT_STORE}/${application_name}-previous/manifests"
     fi
     mv -v "$temp_dir/manifests" "${PERSISTENT_STORE}/${application_name}/"
     $app_sub_module ROLLOUT "${application_name}" "${PERSISTENT_STORE}/${application_name}/manifests"
     if test $? -eq 0; then
-      clean_up "${PERSISTENT_STORE}/${application_name}-${rollback_id}" # clean up call automatically removes the images in by reference taken from clen-up subdirectory, it relies on the fact that we save them there
+      echo "successful rollout"
+      if test -d "${PERSISTENT_STORE}/${application_name}-${rollback_id}"; then
+        clean_up "${PERSISTENT_STORE}/${application_name}-${rollback_id}" # clean up call automatically removes the images in by reference taken from clen-up subdirectory, it relies on the fact that we save them there
+        clean_up "${PERSISTENT_STORE}/${application_name}-previous" # clean up the composition that was running just now
+      else
+        echo "successful rollout: nothing to clean"
+      fi
       # save_rollback "${PERSISTENT_STORE}/${application_name}-${rollback_id}" # saves the current images ids and manifests as new rollback state. this can be just cp -a "${PERSISTENT_STORE}/${application_name} "${PERSISTENT_STORE}/${application_name}-${rollback_id}"
       rm -Rf "${PERSISTENT_STORE}/${application_name}-${rollback_id}"
       cp -a "${PERSISTENT_STORE}/${application_name}" "${PERSISTENT_STORE}/${application_name}-${rollback_id}"
     else
+      echo "unsuccessful rollout"
       clean_up "${PERSISTENT_STORE}/${application_name}"
       $app_sub_module ROLLBACK "${application_name}" "${PERSISTENT_STORE}/${application_name}-${rollback_id}" "${PERSISTENT_STORE}/${application_name}/manifests" # TODO: implement
+      if test $? -eq 0; then
+        echo "successful rollback"
+      else
+        echo "unsuccessful rollback trying to rollout the composition we saw when we started"
+        $app_sub_module ROLLOUT "${application_name}" "${PERSISTENT_STORE}/${application_name}-previous/manifests"
+        if test $? -eq 0; then
+          echo "successfully rolled out ${PERSISTENT_STORE}/${application_name}-previous"
+        else
+          echo "rollout of ${PERSISTENT_STORE}/${application_name}-previous was unsuccessful; deployment failed; rollout attempts failed."
+        fi
+      fi
     fi
     # now if $app_sub_module healthy then rm -Rf "${PERSISTENT_STORE}/${artifact_name}-${rollback_id}"
     # and on rollback we just deploy "${PERSISTENT_STORE}/${artifact_name}-${rollback_id}"
